version: "3"
containers:
- name: packages
  image: quay.io/benjamin_holmes/rh-aap-sandbox-instruqt:latest
  shell: /bin/bash
  memory: 256
  environment:
virtualmachines:
- name: controller
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: hub
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: eda
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: gateway
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: postgres
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n2-standard-4
- name: bastion
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  environment:
    AAP_RUN_INSTALLER: true
  machine_type: n2-standard-4
