version: "3"
containers:
- name: packages
  image: quay.io/benjamin_holmes/rh-aap-sandbox-instruqt:latest
  shell: /bin/bash
  memory: 256
virtualmachines:
- name: aap-controller
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: aap-hub
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: eda-controller
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
- name: postgres
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  machine_type: n1-standard-4
- name: bastion
  image: rhel-cloud/rhel-9
  shell: /bin/bash
  environment:
    RHN_PASSWORD: 
    RHN_USERNAME: 
    RHN_OFFLINE_TOKEN: 
    RHN_AAP_PACKAGE_CHECKSUM: 
  machine_type: n1-standard-2
