#!/bin/bash
set -eo pipefail
##
# This script is used to setup the bastion host for the sandbox...
##

# Allow instruqt time to inject variables and settings
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ] ; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

mkdir -p /opt/ansible/{certs,instruqt-inventory,manifest}

dnf install -y ansible-core policycoreutils-python-utils rsync wget git-core vim 

cat <<'EOF' >> /etc/ansible/ansible.cfg
[defaults]
forks=10
pipelining = True

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
EOF

exit 0