#!/bin/bash
set -eo pipefail
##
# This script is used to setup the bastion host for the sandbox...
##

# Allow instruqt time to inject variables and settings
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ] ; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

mkdir -p /opt/ansible/{certs,instruqt-inventory,manifest}

dnf install -y ansible-core policycoreutils-python-utils rsync

exit 0