#!/bin/bash
set -eo pipefail
##
# This script is used to setup the bastion host for the sandbox...
##

# Allow instruqt time to inject variables and settings
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ] ; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

scp -o StrictHostKeyChecking=no -q -r /opt/ansible/manifest/manifest.zip root@bastion:/opt/ansible/manifest/manifest.zip

pushd /opt/ansible

ansible-playbook setup.yml -e offline_token=$RHN_OFFLINE_TOKEN -e provided_sha_value=$RHN_AAP_PACKAGE_CHECKSUM
scp -o StrictHostKeyChecking=no -q /opt/ansible/aap.tar.gz root@bastion:/opt/ansible/aap.tar.gz

popd

exit 0