#!/bin/bash
set -eo pipefail

grep -q "export=CONFIRM_CLEANUP" /root/.bash_history || fail-message "You have not written export=CONFIRM_CLEANUP into the workstation terminal. Doing so and clicking check will tear down the resources and end the track."

exit 0